// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: grpc_test/infra.proto

package grpc_test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppVersion string `protobuf:"bytes,1,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
}

func (x *AppVersion) Reset() {
	*x = AppVersion{}
	mi := &file_grpc_test_infra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppVersion) ProtoMessage() {}

func (x *AppVersion) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_test_infra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppVersion.ProtoReflect.Descriptor instead.
func (*AppVersion) Descriptor() ([]byte, []int) {
	return file_grpc_test_infra_proto_rawDescGZIP(), []int{0}
}

func (x *AppVersion) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node string `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_grpc_test_infra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_test_infra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_grpc_test_infra_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type Live struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Live string `protobuf:"bytes,1,opt,name=live,proto3" json:"live,omitempty"`
}

func (x *Live) Reset() {
	*x = Live{}
	mi := &file_grpc_test_infra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Live) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Live) ProtoMessage() {}

func (x *Live) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_test_infra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Live.ProtoReflect.Descriptor instead.
func (*Live) Descriptor() ([]byte, []int) {
	return file_grpc_test_infra_proto_rawDescGZIP(), []int{2}
}

func (x *Live) GetLive() string {
	if x != nil {
		return x.Live
	}
	return ""
}

var File_grpc_test_infra_proto protoreflect.FileDescriptor

var file_grpc_test_infra_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x72, 0x63, 0x70, 0x5f, 0x74, 0x65,
	0x73, 0x74, 0x22, 0x2d, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x1a, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x1a, 0x0a,
	0x04, 0x4c, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x32, 0x6b, 0x0a, 0x04, 0x54, 0x65, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x2e, 0x67,
	0x72, 0x63, 0x70, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x1a, 0x0f, 0x2e, 0x67, 0x72, 0x63, 0x70, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x15,
	0x2e, 0x67, 0x72, 0x63, 0x70, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x70, 0x70, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x0f, 0x2e, 0x67, 0x72, 0x63, 0x70, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74,
	0x65, 0x73, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_test_infra_proto_rawDescOnce sync.Once
	file_grpc_test_infra_proto_rawDescData = file_grpc_test_infra_proto_rawDesc
)

func file_grpc_test_infra_proto_rawDescGZIP() []byte {
	file_grpc_test_infra_proto_rawDescOnce.Do(func() {
		file_grpc_test_infra_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_test_infra_proto_rawDescData)
	})
	return file_grpc_test_infra_proto_rawDescData
}

var file_grpc_test_infra_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_test_infra_proto_goTypes = []any{
	(*AppVersion)(nil), // 0: grcp_test.AppVersion
	(*Node)(nil),       // 1: grcp_test.Node
	(*Live)(nil),       // 2: grcp_test.Live
}
var file_grpc_test_infra_proto_depIdxs = []int32{
	0, // 0: grcp_test.Test.GetNode:input_type -> grcp_test.AppVersion
	0, // 1: grcp_test.Test.Health:input_type -> grcp_test.AppVersion
	1, // 2: grcp_test.Test.GetNode:output_type -> grcp_test.Node
	2, // 3: grcp_test.Test.Health:output_type -> grcp_test.Live
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_test_infra_proto_init() }
func file_grpc_test_infra_proto_init() {
	if File_grpc_test_infra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_test_infra_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_test_infra_proto_goTypes,
		DependencyIndexes: file_grpc_test_infra_proto_depIdxs,
		MessageInfos:      file_grpc_test_infra_proto_msgTypes,
	}.Build()
	File_grpc_test_infra_proto = out.File
	file_grpc_test_infra_proto_rawDesc = nil
	file_grpc_test_infra_proto_goTypes = nil
	file_grpc_test_infra_proto_depIdxs = nil
}
